-- Initial schema for ScholarshipOps D1 Database
-- Note: This is a reference SQL migration. 
-- The actual migrations are generated by Drizzle Kit (see drizzle.config.ts)
-- To apply: npx wrangler d1 migrations apply scholarshipops-db --local

-- Leads table
CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  amount TEXT,
  deadline TEXT,
  source TEXT,
  source_type TEXT,
  status TEXT NOT NULL DEFAULT 'qualified',
  eligibility TEXT, -- JSON array stored as TEXT
  notes TEXT,
  added_date TEXT,
  url TEXT,
  match_score INTEGER DEFAULT 0,
  match_reasons TEXT, -- JSON array
  hard_fail_reasons TEXT, -- JSON array
  soft_flags TEXT, -- JSON array
  bucket TEXT,
  http_status INTEGER,
  effort_score INTEGER,
  trust_tier TEXT,
  risk_flags TEXT, -- JSON array
  matched_rule_ids TEXT, -- JSON array
  eligible_countries TEXT, -- JSON array
  is_taiwan_eligible INTEGER, -- Boolean as INTEGER
  taiwan_eligibility_confidence TEXT,
  deadline_date TEXT,
  deadline_label TEXT,
  intake_year TEXT,
  study_start TEXT,
  deadline_confidence TEXT,
  canonical_url TEXT,
  is_directory_page INTEGER DEFAULT 0,
  official_source_url TEXT,
  source_domain TEXT,
  confidence INTEGER, -- Stored as 0-100 instead of float
  eligibility_confidence INTEGER,
  tags TEXT, -- JSON array
  is_index_only INTEGER DEFAULT 0,
  first_seen_at TEXT,
  last_checked_at TEXT,
  next_check_at TEXT,
  persistence_status TEXT,
  source_seed TEXT,
  check_count INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL, -- Timestamp
  updated_at INTEGER NOT NULL -- Timestamp
);

-- Applications table
CREATE TABLE IF NOT EXISTS applications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  deadline TEXT,
  status TEXT NOT NULL DEFAULT 'not_started',
  current_stage TEXT,
  next_action TEXT,
  required_docs TEXT, -- JSON array
  progress INTEGER DEFAULT 0,
  notes TEXT,
  created_at INTEGER NOT NULL, -- Timestamp
  updated_at INTEGER NOT NULL -- Timestamp
);

-- Criteria table
CREATE TABLE IF NOT EXISTS criteria (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  criteria_json TEXT, -- JSON object
  profile_json TEXT, -- JSON object
  updated_at INTEGER NOT NULL -- Timestamp
);

-- Sources table
CREATE TABLE IF NOT EXISTS sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  url TEXT NOT NULL,
  enabled INTEGER DEFAULT 1,
  scraper TEXT,
  priority INTEGER,
  created_at INTEGER NOT NULL, -- Timestamp
  updated_at INTEGER NOT NULL -- Timestamp
);

-- Source health table
CREATE TABLE IF NOT EXISTS source_health (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  source_type TEXT NOT NULL,
  consecutive_failures INTEGER DEFAULT 0,
  total_attempts INTEGER DEFAULT 0,
  total_successes INTEGER DEFAULT 0,
  last_status TEXT NOT NULL DEFAULT 'Unknown',
  last_http_code INTEGER,
  last_error TEXT,
  last_checked TEXT,
  auto_disabled INTEGER DEFAULT 0,
  disabled_reason TEXT,
  updated_at INTEGER NOT NULL -- Timestamp
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_bucket ON leads(bucket);
CREATE INDEX IF NOT EXISTS idx_leads_match_score ON leads(match_score);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_applications_deadline ON applications(deadline);

-- Optimize database
PRAGMA optimize;
