# ScholarshipOps Source Configuration
# Tiered architecture for high-precision scholarship discovery
# 
# Priority System:
#   - Tier 1 (priority: 1): Glasgow-specific - MUST process first
#   - Tier 2 (priority: 2): Portable international scholarships (Chevening, Rotary, etc.)
#   - Tier 3 (priority: 3): Other UK universities (disabled by default for focused search)
#
# Total active sources target: 20-80 (not 800+)

sources:
  # ============================================
  # TIER 1: Glasgow Target University (MUST HAVE)
  # Process these first - highest priority
  # ============================================
  
  - name: "Glasgow All Scholarships"
    type: "university"
    url: "https://www.gla.ac.uk/scholarships/all/"
    enabled: true
    priority: 1
    scraper: "selenium"  # JS-templated listing ({{scholar.title}}); needs browser-render

  - name: "Glasgow Scholarship Search"
    type: "university"
    url: "https://www.gla.ac.uk/scholarships/search/"
    enabled: true
    priority: 1
    scraper: "selenium"  # search UI is also JS-heavy on UofG scholarships

  - name: "Glasgow Scholarships Landing"
    type: "university"
    url: "https://www.gla.ac.uk/scholarships/"
    enabled: true
    priority: 1
    scraper: "university"

  - name: "Glasgow Global Leadership Scholarship"
    type: "university"
    url: "https://www.gla.ac.uk/scholarships/globalleadershipscholarship/"
    enabled: true
    priority: 1
    scraper: "university"

  - name: "Glasgow PGT Fees & Funding"
    type: "university"
    url: "https://www.gla.ac.uk/study/postgraduate/fees-funding/scholarships/"
    enabled: true
    priority: 1
    scraper: "university"

  - name: "Glasgow International Fees & Funding"
    type: "university"
    url: "https://www.gla.ac.uk/international/support/fees-funding/"
    enabled: true
    priority: 1
    scraper: "university"

  - name: "Glasgow Computing Science PGT"
    type: "university"
    url: "https://www.gla.ac.uk/schools/computing/postgraduate/"
    enabled: true
    priority: 1
    scraper: "university"

  - name: "Glasgow Scholarships Portal"
    type: "university"
    url: "https://frontdoor.spa.gla.ac.uk/ScholarshipApp/"
    enabled: true
    priority: 1
    scraper: "selenium"

  # ============================================
  # TIER 2: Portable International Scholarships
  # These can be used at Glasgow or are UK-wide
  # ============================================

  # Major UK Government Scholarships
  - name: "Chevening Scholarships"
    type: "government"
    url: "https://www.chevening.org/scholarships/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "Commonwealth Scholarships"
    type: "government"
    url: "https://cscuk.fcdo.gov.uk/scholarships/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "GREAT Scholarships"
    type: "government"
    url: "https://study-uk.britishcouncil.org/scholarships/great-scholarships"
    enabled: true
    priority: 2
    scraper: "selenium"  # British Council pages often throttle/geo-block; browser fallback helps

  # Major International Foundations
  - name: "Rotary Foundation Global Grants"
    type: "foundation"
    url: "https://www.rotary.org/en/our-programs/scholarships"
    enabled: true
    priority: 2
    scraper: "third_party"

  - name: "Gates Cambridge Scholarship"
    type: "foundation"
    url: "https://www.gatescambridge.org/"
    enabled: true
    priority: 2
    scraper: "third_party"

  - name: "Marshall Scholarship"
    type: "foundation"
    url: "https://www.marshallscholarship.org/"
    enabled: true
    priority: 2
    scraper: "third_party"

  # Taiwan-specific sources
  - name: "Taiwan MOE Overseas Study"
    type: "government"
    url: "https://www.scholarship.moe.gov.tw/"
    enabled: true
    priority: 2
    scraper: "government"

  # Verified Aggregators (high quality)
  - name: "British Council Study UK"
    type: "third_party"
    url: "https://study-uk.britishcouncil.org/scholarships"
    enabled: true
    priority: 2
    scraper: "selenium"  # previously observed 403 in your productions; use browser to reduce blocks

  - name: "FindAPhD - Masters Funding"
    type: "third_party"
    url: "https://www.findamasters.com/funding/"
    enabled: true
    priority: 2
    scraper: "third_party"

  - name: "Prospects Postgrad Funding"
    type: "third_party"
    url: "https://www.prospects.ac.uk/postgraduate-study/funding-postgraduate-study"
    enabled: true
    priority: 2
    scraper: "third_party"

  # Scottish-specific
  - name: "SAAS - Student Awards Agency Scotland"
    type: "government"
    url: "https://www.saas.gov.uk/"
    enabled: false  # generally home-fee aligned; Taiwan applicants typically ineligible
    priority: 2
    scraper: "government"

  - name: "Scotland's Saltire Scholarships"
    type: "government"
    url: "https://www.scotland.org/study/saltire-scholarships"
    enabled: false  # citizenship limited (Canada/China(HK)/India/Japan/Pakistan/USA)
    priority: 2
    scraper: "government"

  # ============================================
  # TIER 3: Other UK Universities (External Links Discovery Only)
  # These are used as "external funding source discoverers", not for collecting their internal scholarships
  # discovery_mode: external_links_only - only extract external links (gov.uk, chevening, etc.)
  # ============================================

  - name: "Edinburgh Scholarships Index"
    type: "university"
    url: "https://www.ed.ac.uk/student-funding/postgraduate/international"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"  # Only extract external links
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"
      - "charitycommission.gov.uk"

  - name: "St Andrews Scholarships Index"
    type: "university"
    url: "https://www.st-andrews.ac.uk/study/fees-and-funding/postgraduate/"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Strathclyde Scholarships Index"
    type: "university"
    url: "https://www.strath.ac.uk/studywithus/scholarships/"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Manchester Scholarships Index"
    type: "university"
    url: "https://www.manchester.ac.uk/study/international/finance/scholarships/"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Birmingham Scholarships Index"
    type: "university"
    url: "https://www.birmingham.ac.uk/international/students/fees-and-funding/scholarships"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Bristol Scholarships Index"
    type: "university"
    url: "https://www.bristol.ac.uk/fees-funding/awards/"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Warwick Scholarships Index"
    type: "university"
    url: "https://warwick.ac.uk/study/international/admissions/finance/scholarships"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Leeds Scholarships Index"
    type: "university"
    url: "https://www.leeds.ac.uk/international-students/doc/fees-scholarships"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Sheffield Scholarships Index"
    type: "university"
    url: "https://www.sheffield.ac.uk/international/funding"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  - name: "Nottingham Scholarships Index"
    type: "university"
    url: "https://www.nottingham.ac.uk/studywithus/international-applicants/scholarships-finance-and-fees/scholarships.aspx"
    enabled: true
    priority: 3
    scraper: "university"
    discovery_mode: "external_links_only"
    allow_domains_outbound:
      - "gov.uk"
      - "fcdo.gov.uk"
      - "cscuk.fcdo.gov.uk"
      - "chevening.org"
      - "rotary.org"
      - "britishcouncil.org"
      - "ukri.org"
      - "sfc.ac.uk"

  # ============================================
  # TIER 4: UK Government & Public Agencies
  # ============================================

  - name: "UKRI - UK Research and Innovation"
    type: "government"
    url: "https://www.ukri.org/opportunity/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "Scottish Funding Council"
    type: "government"
    url: "https://www.sfc.ac.uk/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "GOV.UK Postgraduate Scholarships"
    type: "government"
    url: "https://www.gov.uk/browse/education/student-finance"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "Research Councils UK"
    type: "government"
    url: "https://www.ukri.org/apply-for-funding/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "Arts and Humanities Research Council"
    type: "government"
    url: "https://ahrc.ukri.org/funding/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "Engineering and Physical Sciences Research Council"
    type: "government"
    url: "https://epsrc.ukri.org/funding/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "Economic and Social Research Council"
    type: "government"
    url: "https://esrc.ukri.org/funding/"
    enabled: true
    priority: 2
    scraper: "government"

  - name: "Medical Research Council"
    type: "government"
    url: "https://www.ukri.org/councils/mrc/"
    enabled: true
    priority: 2
    scraper: "government"

  # ============================================
  # TIER 5: Foundations & Industry Scholarships
  # ============================================

  - name: "IEEE Foundation"
    type: "foundation"
    url: "https://www.ieee.org/about/foundation/"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Google Scholarships"
    type: "foundation"
    url: "https://edu.google.com/scholarships/"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Microsoft Scholarships"
    type: "foundation"
    url: "https://www.microsoft.com/en-us/education/scholarships"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Fulbright Commission UK"
    type: "foundation"
    url: "https://www.fulbright.org.uk/"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Rhodes Scholarship"
    type: "foundation"
    url: "https://www.rhodeshouse.ox.ac.uk/scholarships/"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Fulbright UK Awards"
    type: "foundation"
    url: "https://www.fulbright.org.uk/fulbright-awards/"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Wellcome Trust"
    type: "foundation"
    url: "https://wellcome.org/grant-funding"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Leverhulme Trust"
    type: "foundation"
    url: "https://www.leverhulme.ac.uk/"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "Wolfson Foundation"
    type: "foundation"
    url: "https://www.wolfson.org.uk/"
    enabled: true
    priority: 2
    scraper: "foundation"

  - name: "British Council Scholarships"
    type: "foundation"
    url: "https://www.britishcouncil.org/study-work-abroad/in-uk/scholarship-programmes"
    enabled: true
    priority: 2
    scraper: "foundation"

  # ============================================
  # DISABLED: Research-only aggregators
  # Use generate_sources_complete.py for research mode
  # ============================================

  # - name: "Scholarship Portal"
  #   type: "third_party"
  #   url: "https://www.scholarshipportal.com/"
  #   enabled: false
  #   priority: 4
  #   scraper: "third_party"
