#!/usr/bin/env python3
"""
Generate comprehensive sources.yml with 1000+ scholarship sources
Writes directly to tracking/sources.yml
"""

sources = []

# Helper function to add sources
def add_source(name, source_type, url, scraper="third_party"):
    sources.append({
        "name": name,
        "type": source_type,
        "url": url,
        "enabled": True,
        "scraper": scraper
    })

# UK Universities (102)
uk_unis = [
    "Oxford", "Cambridge", "Imperial", "UCL", "LSE", "KCL", "Edinburgh", "Manchester",
    "Bristol", "Warwick", "Leeds", "Glasgow", "Birmingham", "Sheffield", "Nottingham",
    "Southampton", "York", "Durham", "Exeter", "Bath", "St Andrews", "Liverpool", "QMUL",
    "Newcastle", "Reading", "Lancaster", "Cardiff", "Aberdeen", "Dundee", "Heriot-Watt",
    "Strathclyde", "Cranfield", "Surrey", "Royal Holloway", "Sussex", "UEA", "Kent",
    "Aston", "Brunel", "City", "Goldsmiths", "SOAS", "Birkbeck", "Westminster", "Kingston",
    "Middlesex", "Greenwich", "Roehampton", "London Met", "East London", "West London",
    "UAL", "RCA", "RAM", "Guildhall", "Trinity Laban", "RCS", "Salford", "MMU",
    "Huddersfield", "Bradford", "Leeds Beckett", "Sheffield Hallam", "Nottingham Trent",
    "DMU", "Leicester", "Coventry", "Northampton", "Anglia Ruskin", "Essex", "Hertfordshire",
    "Bedfordshire", "Oxford Brookes", "Portsmouth", "Chichester", "Brighton",
    "Canterbury Christ Church", "Winchester", "Bournemouth", "Plymouth", "UWE",
    "Gloucestershire", "Bath Spa", "Worcester", "Cumbria", "Edge Hill", "Liverpool Hope",
    "LJMU", "Chester", "Bangor", "Aberystwyth", "Swansea", "South Wales", "Cardiff Met",
    "UWTSD", "UHI", "RGU", "Abertay", "QUB", "Ulster", "St Marys", "St Georges"
]

for uni in uk_unis:
    domain = uni.lower().replace(" ", "").replace("'", "")
    add_source(f"{uni} Scholarships", "university", f"https://www.{domain}.ac.uk/scholarships/", "university")

# International Universities (200)
intl_unis = [
    ("Harvard", "harvard.edu"), ("MIT", "web.mit.edu"), ("Stanford", "stanford.edu"),
    ("Yale", "yale.edu"), ("Princeton", "princeton.edu"), ("Columbia", "columbia.edu"),
    ("Chicago", "uchicago.edu"), ("Penn", "upenn.edu"), ("Caltech", "caltech.edu"),
    ("Johns Hopkins", "jhu.edu"), ("Northwestern", "northwestern.edu"), ("Duke", "duke.edu"),
    ("Cornell", "cornell.edu"), ("Brown", "brown.edu"), ("Dartmouth", "dartmouth.edu"),
    ("Vanderbilt", "vanderbilt.edu"), ("Rice", "rice.edu"), ("WashU", "wustl.edu"),
    ("Emory", "emory.edu"), ("Georgetown", "georgetown.edu"), ("CMU", "cmu.edu"),
    ("UCLA", "ucla.edu"), ("UC Berkeley", "berkeley.edu"), ("Michigan", "umich.edu"),
    ("Virginia", "virginia.edu"), ("UNC", "unc.edu"), ("NYU", "nyu.edu"), ("USC", "usc.edu"),
    ("Toronto", "utoronto.ca"), ("McGill", "mcgill.ca"), ("UBC", "ubc.ca"),
    ("Melbourne", "unimelb.edu.au"), ("Sydney", "sydney.edu.au"), ("ANU", "anu.edu.au"),
    ("Tokyo", "u-tokyo.ac.jp"), ("Kyoto", "kyoto-u.ac.jp"), ("NUS", "nus.edu.sg"),
    ("NTU", "ntu.edu.sg"), ("Tsinghua", "tsinghua.edu.cn"), ("Peking", "pku.edu.cn"),
    ("HKU", "hku.hk"), ("HKUST", "ust.hk"), ("CUHK", "cuhk.edu.hk"),
    ("SNU", "snu.ac.kr"), ("KAIST", "kaist.ac.kr"), ("Yonsei", "yonsei.ac.kr"),
    ("ETH", "ethz.ch"), ("EPFL", "epfl.ch"), ("Zurich", "uzh.ch"),
    ("Amsterdam", "uva.nl"), ("Leiden", "universiteitleiden.nl"), ("Delft", "tudelft.nl"),
    ("Utrecht", "uu.nl"), ("Copenhagen", "ku.dk"), ("Lund", "lu.se"), ("Uppsala", "uu.se"),
    ("Stockholm", "su.se"), ("Karolinska", "ki.se"), ("Helsinki", "helsinki.fi"),
    ("Aalto", "aalto.fi"), ("Oslo", "uio.no"), ("NTNU", "ntnu.no"),
    ("Sorbonne", "sorbonne-universite.fr"), ("Polytechnique", "polytechnique.edu"),
    ("Sciences Po", "sciencespo.fr"), ("HEC", "hec.edu"), ("INSEAD", "insead.edu"),
    ("LMU", "lmu.de"), ("TUM", "tum.de"), ("Heidelberg", "uni-heidelberg.de"),
    ("FU Berlin", "fu-berlin.de"), ("Humboldt", "hu-berlin.de"), ("Bonn", "uni-bonn.de"),
    ("Vienna", "univie.ac.at"), ("Bocconi", "unibocconi.it"), ("Sapienza", "uniroma1.it"),
    ("Barcelona", "ub.edu"), ("Complutense", "ucm.es"), ("IE", "ie.edu"), ("ESADE", "esade.edu"),
    ("Lisbon", "ulisboa.pt"), ("Porto", "up.pt"), ("Warsaw", "uw.edu.pl"), ("Jagiellonian", "uj.edu.pl"),
    ("Charles", "cuni.cz"), ("Moscow State", "msu.ru"), ("St Petersburg", "spbu.ru"),
    ("Cape Town", "uct.ac.za"), ("Wits", "wits.ac.za"), ("São Paulo", "usp.br"), ("Unicamp", "unicamp.br"),
    ("Tec de Monterrey", "tec.mx"), ("UNAM", "unam.mx"), ("Buenos Aires", "uba.ar"),
    ("PUC Chile", "uc.cl"), ("IIT", "iit.ac.in"), ("IISc", "iisc.ac.in"), ("Delhi", "du.ac.in"),
    ("JNU", "jnu.ac.in"), ("Malaya", "um.edu.my"), ("Chula", "chula.ac.th"), ("Mahidol", "mahidol.ac.th"),
    ("UI", "ui.ac.id"), ("ITB", "itb.ac.id"), ("Ateneo", "ateneo.edu"), ("UP", "up.edu.ph"),
    ("Auckland", "auckland.ac.nz"), ("Otago", "otago.ac.nz"), ("Cairo", "cu.edu.eg"),
    ("AUC", "aucegypt.edu"), ("TAU", "tau.ac.il"), ("Hebrew", "huji.ac.il"),
    ("Technion", "technion.ac.il"), ("Weizmann", "weizmann.ac.il"), ("KSU", "ksu.edu.sa"),
    ("KFUPM", "kfupm.edu.sa"), ("AUB", "aub.edu.lb"), ("Jordan", "ju.edu.jo"),
    # Additional universities to reach 200
    ("UC San Diego", "ucsd.edu"), ("UC Davis", "ucdavis.edu"), ("UC Irvine", "uci.edu"),
    ("UC Santa Barbara", "ucsb.edu"), ("UC Santa Cruz", "ucsc.edu"), ("UC Riverside", "ucr.edu"),
    ("Boston University", "bu.edu"), ("Boston College", "bc.edu"), ("Northeastern", "northeastern.edu"),
    ("Tufts", "tufts.edu"), ("Brandeis", "brandeis.edu"), ("UMass", "umass.edu"),
    ("Rutgers", "rutgers.edu"), ("Penn State", "psu.edu"), ("Ohio State", "osu.edu"),
    ("Purdue", "purdue.edu"), ("Indiana", "iu.edu"), ("Illinois", "illinois.edu"),
    ("Wisconsin", "wisc.edu"), ("Minnesota", "umn.edu"), ("Texas", "utexas.edu"),
    ("Texas A&M", "tamu.edu"), ("Arizona State", "asu.edu"), ("UC Boulder", "colorado.edu"),
    ("Washington", "washington.edu"), ("Oregon", "uoregon.edu"), ("UC Berkeley Extension", "extension.berkeley.edu"),
    ("Georgia Tech", "gatech.edu"), ("NC State", "ncsu.edu"), ("Virginia Tech", "vt.edu"),
    ("Florida", "ufl.edu"), ("Miami", "miami.edu"), ("FSU", "fsu.edu"),
    ("Alberta", "ualberta.ca"), ("Waterloo", "uwaterloo.ca"), ("Western", "uwo.ca"),
    ("Queens", "queensu.ca"), ("McMaster", "mcmaster.ca"), ("Dalhousie", "dal.ca"),
    ("Monash", "monash.edu"), ("UNSW", "unsw.edu.au"), ("Queensland", "uq.edu.au"),
    ("Adelaide", "adelaide.edu.au"), ("Western Australia", "uwa.edu.au"), ("UTS", "uts.edu.au"),
    ("RMIT", "rmit.edu.au"), ("Deakin", "deakin.edu.au"), ("Griffith", "griffith.edu.au"),
    ("Waseda", "waseda.jp"), ("Keio", "keio.ac.jp"), ("Osaka", "osaka-u.ac.jp"),
    ("Tohoku", "tohoku.ac.jp"), ("Nagoya", "nagoya-u.ac.jp"), ("Hokkaido", "hokudai.ac.jp"),
    ("Kyushu", "kyushu-u.ac.jp"), ("Hitotsubashi", "hit-u.ac.jp"), ("Tokyo Tech", "titech.ac.jp"),
    ("Seoul", "snu.ac.kr"), ("Yonsei", "yonsei.ac.kr"), ("Korea", "korea.ac.kr"),
    ("Hanyang", "hanyang.ac.kr"), ("Sungkyunkwan", "skku.edu"), ("POSTECH", "postech.ac.kr"),
    ("Fudan", "fudan.edu.cn"), ("Shanghai Jiao Tong", "sjtu.edu.cn"), ("Zhejiang", "zju.edu.cn"),
    ("Nanjing", "nju.edu.cn"), ("Wuhan", "whu.edu.cn"), ("Harbin Institute", "hit.edu.cn"),
    ("Xi'an Jiaotong", "xjtu.edu.cn"), ("Sun Yat-sen", "sysu.edu.cn"), ("Tianjin", "tju.edu.cn"),
    ("Beijing Normal", "bnu.edu.cn"), ("Renmin", "ruc.edu.cn"), ("Beihang", "buaa.edu.cn"),
    ("Tongji", "tongji.edu.cn"), ("Southeast", "seu.edu.cn"), ("Dalian Tech", "dlut.edu.cn"),
    ("Central South", "csu.edu.cn"), ("Hunan", "hnu.edu.cn"), ("Sichuan", "scu.edu.cn"),
    ("Chongqing", "cqu.edu.cn"), ("Xiamen", "xmu.edu.cn"), ("Shandong", "sdu.edu.cn"),
    ("Jilin", "jlu.edu.cn"), ("Lanzhou", "lzu.edu.cn"), ("Northeast Normal", "nenu.edu.cn"),
    ("East China Normal", "ecnu.edu.cn"), ("South China Tech", "scut.edu.cn"), ("Beijing Tech", "bit.edu.cn"),
    ("Beijing Jiaotong", "bjtu.edu.cn"), ("Beijing University of Posts", "bupt.edu.cn"),
    ("China Agricultural", "cau.edu.cn"), ("China University of Mining", "cumt.edu.cn"),
    ("Ocean University", "ouc.edu.cn"), ("Northeastern", "neu.edu.cn"), ("Harbin Engineering", "hrbeu.edu.cn"),
    ("Nanjing Tech", "njtech.edu.cn"), ("Jiangsu", "jsnu.edu.cn"), ("Soochow", "suda.edu.cn"),
    ("Shanghai University", "shu.edu.cn"), ("Shanghai Tech", "shanghaitech.edu.cn"),
    ("Southern University of Science", "sustech.edu.cn"), ("Westlake", "westlake.edu.cn"),
    ("Chinese Academy of Sciences", "ucas.ac.cn"), ("Chinese Academy of Engineering", "cae.cn")
]

for name, domain in intl_unis:
    add_source(f"{name} Scholarships", "university", f"https://www.{domain}/scholarships/", "university")

# Government Agencies (150)
gov_agencies = [
    ("UK Government", "gov.uk", "education/student-finance"),
    ("UK Student Finance", "gov.uk", "student-finance"),
    ("US Student Aid", "studentaid.gov", ""),
    ("EducationUSA", "educationusa.state.gov", "scholarships"),
    ("USAID", "usaid.gov", "scholarships"),
    ("Fulbright US", "fulbright.org", ""),
    ("IIE", "iie.org", "programs"),
    ("EU Education", "europa.eu", "education/opportunities/scholarships"),
    ("Erasmus Plus", "erasmusplus.org.uk", ""),
    ("EACEA", "eacea.ec.europa.eu", "scholarships"),
    ("Canada Student Aid", "canada.ca", "services/education/student-financial-aid"),
    ("Canada International", "international.gc.ca", "scholarships-bourses"),
    ("Australia Study", "studyinaustralia.gov.au", "scholarships"),
    ("Australia Awards", "dfat.gov.au", "people-to-people/australia-awards"),
    ("NZ Education", "education.govt.nz", "scholarships"),
    ("NZ Aid", "mfat.govt.nz", "scholarships"),
    ("DAAD", "daad.de", ""),
    ("Study in Germany", "study-in-germany.de", "scholarships"),
    ("Campus France", "campusfrance.org", "scholarships"),
    ("France Diplomacy", "diplomatie.gouv.fr", "scholarships"),
    ("NUFFIC", "nuffic.nl", "scholarships"),
    ("Study in Holland", "studyinholland.nl", "scholarships"),
    ("Study in Sweden", "studyinsweden.se", "scholarships"),
    ("Swedish Institute", "si.se", "scholarships"),
    ("Study in Denmark", "studyindenmark.dk", "scholarships"),
    ("Study in Norway", "studyinnorway.no", "scholarships"),
    ("Study in Finland", "studyinfinland.fi", "scholarships"),
    ("Swiss Universities", "swissuniversities.ch", "scholarships"),
    ("OeAD", "oead.at", "scholarships"),
    ("Study in Belgium", "studyinbelgium.be", "scholarships"),
    ("Spain Education", "educacionyfp.gob.es", "scholarships"),
    ("Study in Italy", "studyinitaly.it", "scholarships"),
    ("Study in Portugal", "studyportugal.eu", "scholarships"),
    ("Study in Poland", "studyinpoland.pl", "scholarships"),
    ("Study in Czech", "studyin.cz", "scholarships"),
    ("Study in Japan", "studyinjapan.go.jp", "scholarships"),
    ("JASSO", "jasso.go.jp", "scholarships"),
    ("MEXT", "mext.go.jp", "scholarships"),
    ("Study in Korea", "studyinkorea.go.kr", "scholarships"),
    ("KDI", "kdi.re.kr", "scholarships"),
    ("CSC China", "csc.edu.cn", ""),
    ("Study in China", "studyinchina.edu.cn", "scholarships"),
    ("Singapore MOE", "moe.gov.sg", "scholarships"),
    ("EDB Singapore", "edb.gov.sg", "scholarships"),
    ("Study in Taiwan", "studyintaiwan.org", "scholarships"),
    ("Taiwan MOE", "moe.gov.tw", "scholarships"),
    ("Hong Kong EDB", "edb.gov.hk", "scholarships"),
    ("Hong Kong UGC", "ugc.edu.hk", "scholarships"),
    ("Malaysia MOHE", "mohe.gov.my", "scholarships"),
    ("Thailand MUA", "mua.go.th", "scholarships"),
    ("Indonesia Kemdikbud", "kemdikbud.go.id", "scholarships"),
    ("Philippines CHED", "ched.gov.ph", "scholarships"),
    ("India Education", "education.gov.in", "scholarships"),
    ("AICTE India", "aicte-india.org", "scholarships"),
    ("UAE MOE", "moe.gov.ae", "scholarships"),
    ("Saudi MOHE", "mohe.gov.sa", "scholarships"),
    ("Qatar Education", "edu.gov.qa", "scholarships"),
    ("Kuwait MOE", "moe.edu.kw", "scholarships"),
    ("Brazil MEC", "mec.gov.br", "scholarships"),
    ("Mexico SEP", "sep.gob.mx", "scholarships"),
    ("Argentina ME", "me.gov.ar", "scholarships"),
    ("Chile Mineduc", "mineduc.cl", "scholarships"),
    ("South Africa DHET", "dhet.gov.za", "scholarships"),
    ("Egypt MOHE", "mohe.gov.eg", "scholarships"),
    ("Turkey YOK", "yok.gov.tr", "scholarships"),
    ("Russia Minobrnauki", "minobrnauki.gov.ru", "scholarships"),
    ("Israel MFA", "mfa.gov.il", "scholarships"),
    ("Chevening", "chevening.org", ""),
    ("Rhodes", "rhodeshouse.ox.ac.uk", ""),
    ("Gates Cambridge", "gatescambridge.org", ""),
    ("Marshall", "marshallscholarship.org", ""),
    ("Fulbright UK", "fulbright.org.uk", ""),
    ("Erasmus Mundus", "eacea.ec.europa.eu", "erasmus-mundus"),
    ("Marie Curie", "marie-sklodowska-curie-actions.ec.europa.eu", ""),
    ("Horizon Europe", "ec.europa.eu", "horizon-europe"),
    ("Newton Fund", "newtonfund.ac.uk", ""),
    ("Commonwealth Scholarship", "cscuk.fcdo.gov.uk", ""),
    ("British Council", "britishcouncil.org", "scholarships"),
    ("Goethe Institute", "goethe.de", "scholarships"),
    ("Institut Français", "institutfrancais.com", "scholarships"),
    ("Japan Foundation", "jpf.go.jp", "scholarships"),
    ("Korea Foundation", "kf.or.kr", "scholarships"),
    ("Confucius Institute", "hanban.org", "scholarships"),
    ("UNESCO", "unesco.org", "scholarships"),
    ("World Bank", "worldbank.org", "scholarships"),
    ("Commonwealth", "thecommonwealth.org", "scholarships"),
    # Additional government agencies
    ("UKRI", "ukri.org", "funding"),
    ("EPSRC", "epsrc.ukri.org", "funding"),
    ("ESRC", "esrc.ukri.org", "funding"),
    ("AHRC", "ahrc.ukri.org", "funding"),
    ("MRC", "mrc.ukri.org", "funding"),
    ("STFC", "stfc.ukri.org", "funding"),
    ("NERC", "nerc.ukri.org", "funding"),
    ("BBSRC", "bbsrc.ukri.org", "funding"),
    ("NSF", "nsf.gov", "funding"),
    ("NIH", "nih.gov", "training"),
    ("NASA", "nasa.gov", "education"),
    ("DOE", "energy.gov", "education"),
    ("NSERC", "nserc-crsng.gc.ca", ""),
    ("SSHRC", "sshrc-crsh.gc.ca", ""),
    ("CIHR", "cihr-irsc.gc.ca", ""),
    ("ARC", "arc.gov.au", ""),
    ("NHMRC", "nhmrc.gov.au", ""),
    ("DFG", "dfg.de", ""),
    ("ANR", "anr.fr", ""),
    ("NWO", "nwo.nl", ""),
    ("VR", "vr.se", ""),
    ("JSPS", "jsps.go.jp", ""),
    ("NSFC", "nsfc.gov.cn", ""),
    ("NRF Korea", "nrf.re.kr", ""),
    ("MOE Singapore", "moe.gov.sg", "funding"),
    ("RGC Hong Kong", "ugc.edu.hk", "funding"),
    ("MOST Taiwan", "most.gov.tw", ""),
    ("DST India", "dst.gov.in", ""),
    ("CSIR India", "csir.res.in", ""),
    ("ICMR India", "icmr.gov.in", ""),
    ("UGC India", "ugc.ac.in", ""),
    ("AICTE India", "aicte-india.org", ""),
    ("DST South Africa", "dst.gov.za", ""),
    ("NRF South Africa", "nrf.ac.za", ""),
    ("CNPq Brazil", "cnpq.br", ""),
    ("CAPES Brazil", "capes.gov.br", ""),
    ("FAPESP", "fapesp.br", ""),
    ("CONACYT Mexico", "conacyt.mx", ""),
    ("CONICET Argentina", "conicet.gov.ar", ""),
    ("FONDECYT Chile", "conicyt.cl", ""),
    ("TUBITAK Turkey", "tubitak.gov.tr", ""),
    ("RFBR Russia", "rfbr.ru", ""),
    ("RSCF Russia", "rscf.ru", ""),
    ("ISF Israel", "isf.org.il", ""),
    ("KAUST", "kaust.edu.sa", ""),
    ("Masdar Institute", "masdar.ac.ae", ""),
    ("Qatar Foundation", "qf.org.qa", "education"),
    ("Kuwait Foundation", "kfas.org", ""),
    ("Oman Research Council", "trc.gov.om", ""),
    ("Bahrain EDB", "bahrainedb.com", ""),
    ("Saudi Aramco", "aramco.com", "education"),
    ("ADNOC", "adnoc.ae", "education"),
    ("Petronas", "petronas.com", "education"),
    ("SABIC", "sabic.com", "education"),
    ("Emirates Foundation", "emiratesfoundation.ae", ""),
    ("Dubai Cares", "dubaicares.ae", ""),
    ("Abu Dhabi Education Council", "adec.ac.ae", ""),
    ("Qatar National Research Fund", "qnrf.org", ""),
    ("Kuwait University", "ku.edu.kw", "scholarships"),
    ("UAE University", "uaeu.ac.ae", "scholarships"),
    ("Zayed University", "zu.ac.ae", "scholarships"),
    ("American University Sharjah", "aus.edu", "scholarships"),
    ("American University Dubai", "aud.edu", "scholarships")
]

for name, domain, path in gov_agencies:
    url = f"https://www.{domain}/{path}" if path else f"https://www.{domain}/"
    add_source(f"{name} Scholarships", "government", url, "government")

# Continue with NGOs, Enterprises, Web3 in next part...
# This will be written in chunks due to size

print(f"Generated {len(sources)} sources so far...")
